<a href="https://colab.research.google.com/github/srinath698/statistics-for-data-science-and-ml/blob/main/job_market_analysis(stats).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df=pd.read_csv('/ai_jobs.csv')

In [ ]:
df.head()

,job_id,job_title,company_type,industry,country,city,remote_type,experience_level,min_experience_years,salary_min_usd,salary_max_usd,employment_type,posted_year,company_size
0,0IFD0TVBDIVU,MLOps Engineer,Research Lab,Education,Australia,Remote,Remote,Entry,0,56873,72223,Full-time,2023,Large
1,ZMF8MDD4V30T,Data Analyst,Startup,Education,Germany,Remote,Remote,Entry,0,54803,85599,Full-time,2024,Medium
2,CX1945NQ4FMY,MLOps Engineer,Research Lab,Tech,Canada,Remote,Remote,Senior,5,149980,175806,Full-time,2021,Large
3,QJ7YHL1C32OC,Applied Scientist,Research Lab,Healthcare,Australia,Remote,Remote,Entry,0,53483,86477,Full-time,2023,Medium
4,F0T0PVN9ER14,Machine Learning Engineer,Research Lab,Finance,Australia,Sydney,Hybrid,Mid,2,102977,127298,Full-time,2023,Large

In [ ]:
#application of inferenctial stats
import pandas as pd
import numpy as np

df = pd.read_csv("ai_jobs.csv")
sample = df.sample(n=500, random_state=42)

average_salary_max = sample["salary_max_usd"].mean()
average_salary_min = sample["salary_min_usd"].mean()
average_salary = (average_salary_max + average_salary_min) / 2

print("Estimated Average Salary:", average_salary)

Estimated Average Salary: 113117.746

In [ ]:
import numpy as np

population = np.array([12, 15, 18, 20, 22, 24, 25, 28, 30, 35])

print(population)

[12 15 18 20 22 24 25 28 30 35]

In [ ]:
pop_mean=np.mean(population)
print('pop_mean',pop_mean)

pop_mean 22.9

In [ ]:
pop_var=np.var(population)
print('pop_var',pop_var)

pop_var 44.29

In [ ]:
pop_std=np.std(population)
print('pop_std',pop_std)

pop_std 6.655073252789935

In [ ]:
high_salary=population>=25
pop_prop=np.mean(high_salary)
print('pop_prop',pop_prop)

pop_prop 0.4

In [ ]:
sample = np.array([15, 20, 24, 28, 35,44,55,67])

print(sample)

[15 20 24 28 35 44 55 67]

In [ ]:
sample_mean=np.mean(sample)
print('sample_mean',sample_mean)

sample_mean 36.0

In [ ]:
sample_var=np.var(sample)
print('sample_var',sample_var)

sample_var 286.5

In [ ]:
sample_std=np.std(sample)
print('sample_std',sample_std)

sample_std 16.926310879810757

In [ ]:
sample_prop=np.mean(sample>=25)
print('sample_prop',sample_prop)

sample_prop 0.625

In [ ]:
import pandas as pd
from scipy import stats

df = pd.read_csv("ai_jobs.csv")
salary = df["salary_min_usd"]

ci = stats.t.interval(
    confidence=0.95,
    df=len(salary)-1,
    loc=salary.mean(),
    scale=stats.sem(salary)
)

print(ci)

(np.float64(100546.73230007327), np.float64(101196.13633992673))

In [ ]:
import pandas as pd
from scipy import stats

# df is already loaded in cell SX3TwkuDSclv
salary = df["salary_in_usd"]

se = stats.sem(salary)

print("Standard Error:", se)

Standard Error: 165.68967995380393

In [ ]:
#df=pd.read_csv()

In [ ]:
df['salary_in_usd'] = (df['salary_min_usd'] + df['salary_max_usd']) / 2
display(df.head())

,job_id,job_title,company_type,industry,country,city,remote_type,experience_level,min_experience_years,salary_min_usd,salary_max_usd,employment_type,posted_year,company_size,salary_in_usd
0,0IFD0TVBDIVU,MLOps Engineer,Research Lab,Education,Australia,Remote,Remote,Entry,0,56873,72223,Full-time,2023,Large,64548.0
1,ZMF8MDD4V30T,Data Analyst,Startup,Education,Germany,Remote,Remote,Entry,0,54803,85599,Full-time,2024,Medium,70201.0
2,CX1945NQ4FMY,MLOps Engineer,Research Lab,Tech,Canada,Remote,Remote,Senior,5,149980,175806,Full-time,2021,Large,162893.0
3,QJ7YHL1C32OC,Applied Scientist,Research Lab,Healthcare,Australia,Remote,Remote,Entry,0,53483,86477,Full-time,2023,Medium,69980.0
4,F0T0PVN9ER14,Machine Learning Engineer,Research Lab,Finance,Australia,Sydney,Hybrid,Mid,2,102977,127298,Full-time,2023,Large,115137.5

In [ ]:
import pandas as pd
from scipy import stats

salary = df["salary_in_usd"]

mean = salary.mean()

se = stats.sem(salary)

t_value = stats.t.ppf(0.975, df=len(salary)-1)

moe = t_value * se

print("Sample Mean:", mean)
print("Standard Error:", se)
print("Margin of Error:", moe)

Sample Mean: 110864.89253
Standard Error: 165.68967995380393
Margin of Error: 324.75366688094397

In [ ]:
import numpy as np
from scipy.stats import ttest_1samp

salary = np.array([92000, 95000, 91000, 93000, 96000])

t_stat, p_value = ttest_1samp(salary, popmean=90000)

print("T Statistic:", t_stat)
print("P-value:", p_value)
#got p values as 0.02 so reject the null hypothesis because we know that p>0.05 t0 not reject the h0

T Statistic: 3.6663142889169062
P-value: 0.021460634376892287

In [ ]:
import numpy as np
from scipy.stats import ttest_ind

remote = np.array([95000,98000,102000,97000,99000])
onsite = np.array([85000,87000,90000,88000,86000])
t_stat, p_value = ttest_ind(remote, onsite)
print("P-value:", p_value)

P-value: 6.146911519437684e-05

In [ ]:
import numpy as np
from scipy.stats import ttest_ind
model_A = np.array([89,90,88,89,90,91,89,88,90,89])
model_B = np.array([91,92,90,91,92,93,91,90,92,91])
t_stat, p_value = ttest_ind(model_A, model_B)

print("P-value:", p_value)
#also here p value is < 0.05 so we reject h0

P-value: 0.00017304393340073743

In [ ]:
import numpy as np
from scipy.stats import ttest_ind

model_A = np.array([89,90,88,89,90,91,89])

model_B = np.array([91,92,90,91,92,93,91])
t_stat, p_value = ttest_ind(model_A, model_B)
print("P-value:", p_value)

alpha = 0.05
if p_value < alpha:
    print("Reject H₀")
else:
    print("Fail to Reject H₀")

P-value: 0.0023779804411942916
Reject H₀

In [ ]:
import pandas as pd

print(df["salary_in_usd"].skew())

0.13025770455527896

In [ ]:
print(df["salary_in_usd"].kurtosis())

-1.4611154343320305